const express = require('express');
const router = express.Router();
const controller = require('../controllers/usuariosController');
router.get('/', controller.getAll);
router.get('/:id', controller.getById);
router.post('/', controller.create);
router.put('/:id', controller.update);
router.delete('/:id', controller.delete);
router.post('/login', controller.login);
module.exports = router;